export enum SkillsTitleEnum {
  // Front end
  html = 'HTML',
  css = 'CSS',
  sass = 'SASS',
  javascript = 'JavaScript',
  typescript = 'TypeScript',
  angular = 'Angular',
  angularMaterial = 'Angular Material',
  rxjs = 'RxJs',
  ngrx = 'NgRx',
  storybook = 'Storybook',
  jest = 'Jest',
  karma = 'Karma',
  // Back end
  java = 'Java',
  spring = 'Spring',
  hibernate = 'Hibernate',
  postgreSQL = 'PostgreSQL',
  junit = 'JUnit',
  nodejs = 'Node.js',
  express = 'Express.js',
  socketIo = 'Socket.IO',
  // Tools
  docker = 'Docker',
  git = 'Git',
  gitHub = 'GitHub',
  gitLab = 'GitLab',
  npm = 'NPM',
  pnpm = 'PNPM',
  eslint = 'ESLint',
  postman = 'Postman',
  windows11 = 'Windows',
  linux = 'Linux',
  intellij = 'IntelliJ IDEA',
  vscode = 'Visual Studio Code',
}

export enum SkillsClassNameEnum {
  // Front end
  html = 'devicon-html5-plain',
  css = 'devicon-css3-plain',
  sass = 'devicon-sass-original',
  javascript = 'devicon-javascript-plain',
  typescript = 'devicon-typescript-plain',
  angular = 'devicon-angularjs-plain',
  angularMaterial = 'devicon-angularmaterial-plain',
  rxjs = 'devicon-rxjs-plain',
  ngrx = 'devicon-ngrx-plain',
  storybook = 'devicon-storybook-plain',
  jest = 'devicon-jest-plain',
  karma = 'devicon-karma-plain',
  // Back end
  java = 'devicon-java-plain',
  spring = 'devicon-spring-original',
  hibernate = 'devicon-hibernate-plain',
  postgreSQL = 'devicon-postgresql-plain',
  junit = 'devicon-junit-plain',
  nodejs = 'devicon-nodejs-plain',
  express = 'devicon-express-original',
  socketIo = 'devicon-socketio-original',
  // Tools
  docker = 'devicon-docker-plain',
  git = 'devicon-git-plain',
  gitHub = 'devicon-github-plain',
  gitLab = 'devicon-gitlab-plain',
  npm = 'devicon-npm-original-wordmark',
  pnpm = 'devicon-pnpm-plain',
  eslint = 'devicon-eslint-plain',
  postman = 'devicon-postman-plain',
  windows11 = 'devicon-windows11-original',
  linux = 'devicon-linux-plain',
  intellij = 'devicon-intellij-plain',
  vscode = 'devicon-vscode-plain',
}
