export type TechnologyLabelType =
  | 'HTML'
  | 'CSS'
  | 'Sass'
  | 'JavaScript'
  | 'TypeScript'
  | 'Python'
  | 'Angular'
  | 'RxJS'
  | 'Storybook'
  | 'PrimeNG'
  | 'NumPy'
  | 'Jest'
  | 'PostgreSQL'
  | 'Microsoft SQL Server'
  | 'NGINX'
  | 'Node.js'
  | 'Docker'
  | 'SnapLogic'
  | 'n8n'
  | 'Git'
  | 'GitHub'
  | 'GitLab'
  | 'npm'
  | 'pnpm'
  | 'Eslint'
  | 'Prettier'
  | 'Stylelint'
  | 'Postman'
  | 'Nx'
  | 'Visual Paradigm'
  | 'WebStorm'
  | 'Visual Studio Code'
  | 'Eclipse'
  | 'Jira'
  | 'Windows'
  | 'Linux';
