import { TechnologyStateModel } from './technology-state.model';
import { SvgConst } from '../../const/svg.const';

export const TechnologyConst: TechnologyStateModel = {
  html: {
    id: 'html',
    name: 'HTML',
    level: 'beginner',
    ownGroups: ['frontend'],
    groups: {
      aprSystem: ['frontend'],
      primaris: [],
    },
    category: 'markupLanguage',
    icon: SvgConst.html,
    order: 0,
  },
  css: {
    id: 'css',
    name: 'CSS',
    level: 'beginner',
    ownGroups: ['frontend'],
    groups: {
      aprSystem: ['frontend'],
      primaris: [],
    },
    category: 'stylesheetLanguage',
    icon: SvgConst.css,
    order: 0,
  },
  sass: {
    id: 'sass',
    name: 'Sass',
    level: 'beginner',
    ownGroups: ['frontend'],
    groups: {
      aprSystem: ['frontend'],
      primaris: [],
    },
    category: 'stylesheetLanguage',
    icon: SvgConst.sass,
    order: 1,
  },
  javascript: {
    id: 'javascript',
    name: 'JavaScript',
    level: 'beginner',
    ownGroups: ['frontend', 'backend'],
    groups: {
      aprSystem: ['frontend', 'backend'],
      primaris: ['integration'],
    },
    category: 'programmingLanguage',
    icon: SvgConst.javascript,
    order: 0,
  },
  typescript: {
    id: 'typescript',
    name: 'TypeScript',
    level: 'beginner',
    ownGroups: ['frontend', 'backend'],
    groups: {
      aprSystem: ['frontend', 'backend'],
      primaris: [],
    },
    category: 'programmingLanguage',
    icon: SvgConst.typescript,
    order: 1,
  },
  python: {
    id: 'python',
    name: 'Python',
    level: 'beginner',
    ownGroups: ['ai'],
    groups: {
      aprSystem: [],
      primaris: [],
    },
    category: 'programmingLanguage',
    icon: SvgConst.python,
    order: 2,
  },
  angular: {
    id: 'angular',
    name: 'Angular',
    level: 'beginner',
    ownGroups: ['frontend'],
    groups: {
      aprSystem: ['frontend'],
      primaris: [],
    },
    category: 'framework',
    icon: SvgConst.angular,
    order: 0,
  },
  rxjs: {
    id: 'rxjs',
    name: 'RxJS',
    level: 'beginner',
    ownGroups: ['frontend'],
    groups: {
      aprSystem: ['frontend'],
      primaris: [],
    },
    category: 'library',
    icon: SvgConst.rxjs,
    order: 0,
  },
  storybook: {
    id: 'storybook',
    name: 'Storybook',
    level: 'beginner',
    ownGroups: ['frontend'],
    groups: {
      aprSystem: ['frontend'],
      primaris: [],
    },
    category: 'library',
    icon: SvgConst.storybook,
    order: 1,
  },
  primeng: {
    id: 'primeng',
    name: 'PrimeNG',
    level: 'beginner',
    ownGroups: ['frontend'],
    groups: {
      aprSystem: ['frontend'],
      primaris: [],
    },
    category: 'library',
    icon: SvgConst.primeng,
    order: 2,
  },
  numpy: {
    id: 'numpy',
    name: 'NumPy',
    level: 'beginner',
    ownGroups: ['ai'],
    groups: {
      aprSystem: [],
      primaris: [],
    },
    category: 'library',
    icon: SvgConst.numpy,
    order: 3,
  },
  jest: {
    id: 'jest',
    name: 'Jest',
    level: 'beginner',
    ownGroups: ['frontend'],
    groups: {
      aprSystem: ['frontend'],
      primaris: [],
    },
    category: 'test',
    icon: SvgConst.jest,
    order: 0,
  },
  eslint: {
    id: 'eslint',
    name: 'Eslint',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: [],
    },
    category: 'codeQuality',
    icon: SvgConst.eslint,
    order: 0,
  },
  prettier: {
    id: 'prettier',
    name: 'Prettier',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: [],
    },
    category: 'codeQuality',
    icon: SvgConst.prettier,
    order: 1,
  },
  stylelint: {
    id: 'stylelint',
    name: 'Stylelint',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: [],
    },
    category: 'codeQuality',
    icon: SvgConst.stylelint,
    order: 2,
  },
  postgresql: {
    id: 'postgresql',
    name: 'PostgreSQL',
    level: 'beginner',
    ownGroups: ['backend'],
    groups: {
      aprSystem: ['backend'],
      primaris: [],
    },
    category: 'database',
    icon: SvgConst.postgresql,
    order: 0,
  },
  microsoftSqlServer: {
    id: 'microsoftSqlServer',
    name: 'Microsoft SQL Server',
    level: 'beginner',
    ownGroups: ['backend'],
    groups: {
      aprSystem: [],
      primaris: ['integration'],
    },
    category: 'database',
    icon: SvgConst.microsoftSqlServer,
    order: 1,
  },
  nginx: {
    id: 'nginx',
    name: 'NGINX',
    level: 'beginner',
    ownGroups: ['devops'],
    groups: {
      aprSystem: ['devops'],
      primaris: [],
    },
    category: 'server',
    icon: SvgConst.nginx,
    order: 0,
  },
  nodejs: {
    id: 'nodejs',
    name: 'Node.js',
    level: 'beginner',
    ownGroups: ['backend'],
    groups: {
      aprSystem: ['backend'],
      primaris: [],
    },
    category: 'runtime',
    icon: SvgConst.nodejs,
    order: 0,
  },
  docker: {
    id: 'docker',
    name: 'Docker',
    level: 'beginner',
    ownGroups: ['devops'],
    groups: {
      aprSystem: ['devops'],
      primaris: [],
    },
    category: 'containerization',
    icon: SvgConst.docker,
    order: 0,
  },
  snaplogic: {
    id: 'snaplogic',
    name: 'SnapLogic',
    level: 'beginner',
    ownGroups: [],
    groups: {
      aprSystem: [],
      primaris: ['integration'],
    },
    category: 'integrationPlatform',
    icon: SvgConst.snaplogic,
    order: 0,
  },
  n8n: {
    id: 'n8n',
    name: 'N8N',
    level: 'beginner',
    ownGroups: ['integration'],
    groups: {
      aprSystem: [],
      primaris: [],
    },
    category: 'integrationPlatform',
    icon: SvgConst.n8n,
    order: 1,
  },
  postman: {
    id: 'postman',
    name: 'Postman',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: ['common'],
    },
    category: 'api',
    icon: SvgConst.postman,
    order: 0,
  },
  git: {
    id: 'git',
    name: 'Git',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: [],
    },
    category: 'versionControlSystem',
    icon: SvgConst.git,
    order: 0,
  },
  github: {
    id: 'github',
    name: 'GitHub',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: [],
      primaris: ['common'],
    },
    category: 'versionControlSystem',
    icon: SvgConst.github,
    order: 1,
  },
  gitlab: {
    id: 'gitlab',
    name: 'GitLab',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: [],
    },
    category: 'versionControlSystem',
    icon: SvgConst.gitlab,
    order: 2,
  },
  npm: {
    id: 'npm',
    name: 'npm',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: [],
    },
    category: 'packageManager',
    icon: SvgConst.npm,
    order: 0,
  },
  pnpm: {
    id: 'pnpm',
    name: 'pnpm',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: [],
    },
    category: 'packageManager',
    icon: SvgConst.pnpm,
    order: 1,
  },
  nx: {
    id: 'nx',
    name: 'Nx',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: [],
    },
    category: 'monorepo',
    icon: SvgConst.nx,
    order: 0,
  },
  webstorm: {
    id: 'webstorm',
    name: 'WebStorm',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: [],
    },
    category: 'ide',
    icon: SvgConst.webstorm,
    order: 0,
  },
  eclipse: {
    id: 'eclipse',
    name: 'Eclipse',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: [],
      primaris: [],
    },
    category: 'ide',
    icon: SvgConst.eclipse,
    order: 1,
  },
  visualStudioCode: {
    id: 'visualStudioCode',
    name: 'Visual Studio Code',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: [],
    },
    category: 'editor',
    icon: SvgConst.visualStudioCode,
    order: 0,
  },
  visualParadigm: {
    id: 'visualParadigm',
    name: 'Visual Paradigm',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: [],
      primaris: [],
    },
    category: 'diagram',
    icon: SvgConst.visualParadigm,
    order: 0,
  },
  jira: {
    id: 'jira',
    name: 'Jira',
    level: 'beginner',
    ownGroups: [],
    groups: {
      aprSystem: [],
      primaris: ['common'],
    },
    category: 'projectManagement',
    icon: SvgConst.jira,
    order: 0,
  },
  windows: {
    id: 'windows',
    name: 'Windows',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: ['common'],
      primaris: ['common'],
    },
    category: 'operatingSystem',
    icon: SvgConst.window,
    order: 0,
  },
  linux: {
    id: 'linux',
    name: 'Linux',
    level: 'beginner',
    ownGroups: ['common'],
    groups: {
      aprSystem: [],
      primaris: [],
    },
    category: 'operatingSystem',
    icon: SvgConst.linux,
    order: 1,
  },
};
