import { Selector, State } from '@ngxs/store';
import { Injectable } from '@angular/core';

import { TechnologyStateModel } from './technology-state.model';
import { SvgConst } from '../../const/svg.const';

@State<TechnologyStateModel>({
  name: 'technology',
  defaults: {
    html: {
      name: 'HTML',
      level: 'beginner',
      category: 'markupLanguage',
      icon: SvgConst.html,
      order: 0,
    },
    css: {
      name: 'CSS',
      level: 'beginner',
      category: 'stylesheetLanguage',
      icon: SvgConst.css,
      order: 0,
    },
    sass: {
      name: 'Sass',
      level: 'beginner',
      category: 'stylesheetLanguage',
      icon: SvgConst.sass,
      order: 1,
    },
    javascript: {
      name: 'JavaScript',
      level: 'beginner',
      category: 'programmingLanguage',
      icon: SvgConst.javascript,
      order: 0,
    },
    typescript: {
      name: 'TypeScript',
      level: 'beginner',
      category: 'programmingLanguage',
      icon: SvgConst.typescript,
      order: 1,
    },
    python: {
      name: 'Python',
      level: 'beginner',
      category: 'programmingLanguage',
      icon: SvgConst.python,
      order: 2,
    },
    angular: {
      name: 'Angular',
      level: 'beginner',
      category: 'framework',
      icon: SvgConst.angular,
      order: 0,
    },
    rxjs: {
      name: 'RxJS',
      level: 'beginner',
      category: 'library',
      icon: SvgConst.rxjs,
      order: 0,
    },
    storybook: {
      name: 'Storybook',
      level: 'beginner',
      category: 'library',
      icon: SvgConst.storybook,
      order: 1,
    },
    primeng: {
      name: 'PrimeNG',
      level: 'beginner',
      category: 'library',
      icon: SvgConst.primeng,
      order: 2,
    },
    numpy: {
      name: 'NumPy',
      level: 'beginner',
      category: 'library',
      icon: SvgConst.numpy,
      order: 3,
    },
    jest: {
      name: 'Jest',
      level: 'beginner',
      category: 'test',
      icon: SvgConst.jest,
      order: 0,
    },
    eslint: {
      name: 'Eslint',
      level: 'beginner',
      category: 'codeQuality',
      icon: SvgConst.eslint,
      order: 0,
    },
    prettier: {
      name: 'Prettier',
      level: 'beginner',
      category: 'codeQuality',
      icon: SvgConst.prettier,
      order: 1,
    },
    stylelint: {
      name: 'Stylelint',
      level: 'beginner',
      category: 'codeQuality',
      icon: SvgConst.stylelint,
      order: 2,
    },
    postgresql: {
      name: 'PostgreSQL',
      level: 'beginner',
      category: 'database',
      icon: SvgConst.postgresql,
      order: 0,
    },
    microsoftSqlServer: {
      name: 'Microsoft SQL Server',
      level: 'beginner',
      category: 'database',
      icon: SvgConst.microsoftSqlServer,
      order: 1,
    },
    nginx: {
      name: 'NGINX',
      level: 'beginner',
      category: 'server',
      icon: SvgConst.nginx,
      order: 0,
    },
    nodejs: {
      name: 'Node.js',
      level: 'beginner',
      category: 'runtime',
      icon: SvgConst.nodejs,
      order: 0,
    },
    docker: {
      name: 'Docker',
      level: 'beginner',
      category: 'containerization',
      icon: SvgConst.docker,
      order: 0,
    },
    snaplogic: {
      name: 'SnapLogic',
      level: 'beginner',
      category: 'integrationPlatform',
      icon: SvgConst.snaplogic,
      order: 0,
    },
    n8n: {
      name: 'N8N',
      level: 'beginner',
      category: 'integrationPlatform',
      icon: SvgConst.n8n,
      order: 1,
    },
    postman: {
      name: 'Postman',
      level: 'beginner',
      category: 'api',
      icon: SvgConst.postman,
      order: 0,
    },
    git: {
      name: 'Git',
      level: 'beginner',
      category: 'versionControlSystem',
      icon: SvgConst.git,
      order: 0,
    },
    github: {
      name: 'GitHub',
      level: 'beginner',
      category: 'versionControlSystem',
      icon: SvgConst.github,
      order: 1,
    },
    gitlab: {
      name: 'GitLab',
      level: 'beginner',
      category: 'versionControlSystem',
      icon: SvgConst.gitlab,
      order: 2,
    },
    npm: {
      name: 'npm',
      level: 'beginner',
      category: 'packageManager',
      icon: SvgConst.npm,
      order: 0,
    },
    pnpm: {
      name: 'pnpm',
      level: 'beginner',
      category: 'packageManager',
      icon: SvgConst.pnpm,
      order: 1,
    },
    nx: {
      name: 'Nx',
      level: 'beginner',
      category: 'monorepo',
      icon: SvgConst.nx,
      order: 0,
    },
    webstorm: {
      name: 'WebStorm',
      level: 'beginner',
      category: 'ide',
      icon: SvgConst.webstorm,
      order: 0,
    },
    eclipse: {
      name: 'Eclipse',
      level: 'beginner',
      category: 'ide',
      icon: SvgConst.eclipse,
      order: 1,
    },
    visualStudioCode: {
      name: 'Visual Studio Code',
      level: 'beginner',
      category: 'editor',
      icon: SvgConst.visualStudioCode,
      order: 0,
    },
    visualParadigm: {
      name: 'Visual Paradigm',
      level: 'beginner',
      category: 'diagram',
      icon: SvgConst.visualParadigm,
      order: 0,
    },
    jira: {
      name: 'Jira',
      level: 'beginner',
      category: 'projectManagement',
      icon: SvgConst.jira,
      order: 0,
    },
    windows: {
      name: 'Windows',
      level: 'beginner',
      category: 'operatingSystem',
      icon: SvgConst.window,
      order: 0,
    },
    linux: {
      name: 'Linux',
      level: 'beginner',
      category: 'operatingSystem',
      icon: SvgConst.linux,
      order: 1,
    },
  },
})
@Injectable()
export class TechnologyState {
  @Selector()
  static getState(state: TechnologyStateModel) {
    return state;
  }
}
