export type TechnologyCategoryType =
  | 'markupLanguage'
  | 'styleLanguage'
  | 'programmingLanguage'
  | 'framework'
  | 'library'
  | 'test'
  | 'database'
  | 'server'
  | 'runtime'
  | 'containerization'
  | 'integration'
  | 'versionControlSystem'
  | 'packageManager'
  | 'codeQuality'
  | 'developerTool'
  | 'operatingSystem';
