export enum CategoryKindEnum {
  markupLanguage = 'markupLanguage',
  styleLanguage = 'styleLanguage',
  programmingLanguage = 'programmingLanguage',
  framework = 'framework',
  library = 'library',
  test = 'test',
  database = 'database',
  server = 'server',
  runtime = 'runtime',
  containerization = 'containerization',
  integration = 'integration',
  versionControlSystem = 'versionControlSystem',
  packageManager = 'packageManager',
  codeQuality = 'codeQuality',
  developerTool = 'developerTool',
  operatingSystem = 'operatingSystem',
}
