export type TechnologyCategoryNameDataType =
  | 'Markup Language'
  | 'Stylesheet Language'
  | 'Programming Language'
  | 'Framework'
  | 'Library'
  | 'Test'
  | 'Code Quality'
  | 'Database'
  | 'Server'
  | 'Runtime'
  | 'Containerization'
  | 'Integration Platform'
  | 'API'
  | 'Version Control System'
  | 'Package Manager'
  | 'Monorepo'
  | 'IDE'
  | 'Editor'
  | 'Diagram'
  | 'Project Management'
  | 'Operating System';
